# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'YJUIKit',:git=>'http://39.108.16.93:20081/yinq/YJUIKit.git'
pod 'IQKeyboardManager'
pod 'FDFullscreenPopGesture'
pod 'SDWebImage'

target 'ButterflyDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ButterflyDemo

end
